// <auto-generated />
namespace LG.DLFinance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class emailchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emailchange));
        
        string IMigrationMetadata.Id
        {
            get { return "201708031223345_emailchange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
