// <auto-generated />
namespace LG.DLFinance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class jackpot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jackpot));
        
        string IMigrationMetadata.Id
        {
            get { return "201808072254569_jackpot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
